name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: label when approved
    runs-on: ubuntu-latest
    steps:
    - name: label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "2"
        ADD_LABEL: "Ready to Merge"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
